#!/bin/sh

# server/ 配下に変更があるか
if git diff --quiet --exit-code  -- ./adapter; then
  echo "Running change db schema information ..."
#   cargo sqlx prepare > /dev/null 2>&1; git add .sqlx > /dev/null
else
  echo "No changes detected in ./adapter"
fi