#!/bin/sh

# update .sqlx on migration and repository changed adapter
if git diff --quiet --exit-code  -- ./adapter; then
  echo "Running change db schema information ..."
  cargo sqlx prepare > /dev/null 2>&1; git add .sqlx > /dev/null
else
  echo " Nochanges detected in ./adapter"
fi

# if git diff --quiet --exit-code -- ./src; then
#     echo "Running cargo fmt and clippy..."
#     cargo fmt
#     cargo clippy --fix
# else
#     echo "No changes detected in ./src"
# fi