@accessToken = {{login.response.body.accessToken}}

###  health

GET http://localhost:8080/api/v1/health HTTP/1.1
content-type: application/json

###  login

# @name login
POST http://localhost:8080/auth/login HTTP/1.1
Authorization: {{accessToken}}
content-type: application/json

{
    "email": "elezar.fig@example.com",
    "password": "password"
}

###  users index


GET http://localhost:8080/api/v1/users HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

###  user create

POST http://localhost:8080/api/v1/users HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "name": "hiro",
    "email": "lapis@example.com",
    "password": "eighthofmarch"
}

###  book index

GET http://localhost:8080/api/v1/books?limit=1&offset=0 HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

###  book index (error pattern of query parameter)

GET http://localhost:8080/api/v1/books?limit=1&offset=aaa HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json


###  book create

POST http://localhost:8080/api/v1/books HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "title": "how to develop rust api",
    "author": "hiro-lapis",
    "isbn": "4649",
    "description": "Rust was named for the group of fungi that are over-engineered for survival"
}


### checkout

POST http://localhost:8080/v1/books/{{bookId}} HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json


{
    "name": "hiro",
    "email": "lapis@example.com",
    "password": "eighthofmarch"
}
